backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: blog
    label: Blog
    folder: source/posts/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Body, name: body, widget: markdown}

  - name: story
    label: Story
    folder: source/stories/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Benefit, name: benefit, widget: string}
      - {label: How To, name: howto, widget: string}
      - {label: Faq, name: faq, widget: string}