backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: blog
    label: Blog
    folder: source/posts/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Body, name: body, widget: markdown}

  - name: story
    label: Story
    folder: source/stories/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Benefit, name: benefit, widget: string}
      - {label: How To, name: howto, widget: string}
      - {label: Faq, name: faq, widget: string}
      
  - name: products
    label: Products
    files:
      - label: Product List
        name: product-list
        file: data/products.yml
        widget: list
        fields:
          - {label: Name, name: name, required: true, widget: string}
          - {label: Description, name: description, required: true, widget: string}

  - name: pages
    label: Pages
    format: yml
    extension: yml
    folder: data/pages/
    create: true
    slug: '{{title}}'
    fields:
      - label: Header
        name: header
        widget: image
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Layout
        name: layout
        widget: select
        options: ['normal', ' new_school', ' parent']
        default: ''